### PR TITLE
Watchdog for libcamera-apps.

### PR DESCRIPTION
**Pull request by tmsd2001**
try again, I hope this time it's right

### CODE REVIEW

**Comment by davidplowman** [comment]
Hi, thanks for submitting this. It wasn't terribly clear to me what this script does, why I might need it and how I would use it. Could you explain some of that, please? Thanks.

**Comment by tmsd2001** [comment]
In my case it often happens that the app no ​​longer runs, although the process is still active with 1% CPU use. In this case the Script kill the App and restart then. You can also use it to automatically start the app after boot , and other ways the camera stopped working.
thought for example for 24/7 cameras.
However, I already have another version.

**Comment by davidplowman** [comment]
Thanks for the update. The first thing I'd like to do is understand the underlying problem better because it sounds like maybe something isn't working correctly. Are you able to give instructions that will provoke it and file an issue that we can then look at? Thanks!

**Comment by tmsd2001** [comment]
I had already opened one.
[https://github.com/raspberrypi/libcamera-apps/issues/354#issue-1358593762](url)

**Pull request closed without merging**
