### PR TITLE
Colour spaces

### PR DESCRIPTION
**Pull request by davidplowman**
Still WIP - don't merge!

### CODE REVIEW

**Comment by davidplowman** [comment]
I don't think I'm planning to do any more on this, so I guess that makes it ready for review.

I've rewritten the DRM stuff a bit. Previously I was duplicating the kernel enums so that I could use them directly (they don't seem to be provided to userspace). Now I'm searching for the correct enum values by matching strings - DRM does appear to provide name-to-value lookup tables. But I still don't particularly like it.

**Comment by naushir** [comment]
Should we submit this change now?

**Comment by davidplowman** [comment]
Well, I'm "happy enough" with it, though I can't say I love the messing around with DRM. But it would be good to commit it before we release our updated versions of everything, I think.

**Comment by naushir** [comment]
Done!

**Pull request merged**
